# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_edit_at', models.DateTimeField(auto_now_add=True, help_text='Datetime that this object was last edited.')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FOOD', '먹을 곳'), ('PLACE', '갈 곳'), ('TODO', '할 것')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
