# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
