# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170517_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_edit_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime that this object was last edited.'),
        ),
    ]
