# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20170517_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edit_at', models.DateTimeField(auto_now=True, help_text='Datetime that this object was last edited.')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(blank=True, to='todo.Tag'),
        ),
    ]
