# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20170519_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_complete_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
